all: lista-1.pdf lista-2.pdf

lista-1.pdf: lista-1.tex
	pdflatex lista-1.tex

lista-2.pdf: lista-2.tex
	pdflatex lista-2.tex

lista-3.pdf: lista-3.tex
	pdflatex lista-3.tex

clean:
	@rm lista-*.pdf *.log *.aux
